name: Autobuild BDBuilder

# Controls when the action will run.
on:
  push:
    branches:
      - master
      - feature/*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: build and publish
    runs-on: ubuntu-latest

    steps:
      - name: clean working directory
        run: rm -rf /home/runner/work/${{ github.repository }}

      - name: checkout code
        uses: actions/checkout@v2

      - name: setup nodejs
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: install dependencies
        run: npm i

      - name: build core
        run: npm run build

      - name: publish
        id: publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ github.token }}
          access: public
          registry: https://npm.pkg.github.com
          tag: latest
          check-version: false

      - name: detect version change
        if: steps.publish.outputs.type != 'none'
        run: |
          echo "Version changed: ${{ steps.publish.outputs.old-version }} => ${{ steps.publish.outputs.version }}"
